TYPE: when

# whether use comment
USE_COMMENT: False

# whether use file context
USE_FILE_CONTEXT: False

# if use file context, how many lines before
LINE_BEFORE: 10

# whether use import message
USE_IMPORT_MESSAGE: False

# whether fill in the middle (use right context)
FILL_IN_THE_MIDDLE: False

SAVE_FILE_NAME: generated/when_to_use_function